version: '3.9'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    ports:
      - "8000:8000"
    volumes:
      - ./api:/app/api
    environment:
      DATABASE_URL: postgresql://postgres:pass@db:5432/burn_note
    depends_on:
      - db

  db:
    image: postgres:15
    environment:
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: burn_note
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    platform: linux/amd64
    build:
      context: ./web
      dockerfile: ../Dockerfile.web
    ports:
      - "5173:5173"
    volumes:
      - ./web:/app
      - node_modules:/app/node_modules
    working_dir: /app
    command: npm run dev -- --host

volumes:
  node_modules:
  postgres_data:
