# Generated by Django 5.2.1 on 2025-05-20 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SecretMessage',
            fields=[
                ('token', models.CharField(max_length=40, primary_key=True, serialize=False, unique=True)),
                ('encrypted_message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
            ],
        ),
    ]
